// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBsEMFmu2w8PqtTTle-PHhvBkdH30Tny8',
    appId: '1:988144449753:web:ed50cfbf050dfddbad66c8',
    messagingSenderId: '988144449753',
    projectId: 'animation-170f1',
    authDomain: 'animation-170f1.firebaseapp.com',
    databaseURL: 'https://animation-170f1-default-rtdb.firebaseio.com',
    storageBucket: 'animation-170f1.firebasestorage.app',
    measurementId: 'G-Z3EZ775J6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7zRwwLnlzs8pan3Pd9YlQe7_Op7eSJ3c',
    appId: '1:988144449753:android:cf22513aa23843fbad66c8',
    messagingSenderId: '988144449753',
    projectId: 'animation-170f1',
    databaseURL: 'https://animation-170f1-default-rtdb.firebaseio.com',
    storageBucket: 'animation-170f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZjWFf4vcso4imGJbE9o7pyGK0Z_ZA5yc',
    appId: '1:988144449753:ios:904afbdc99afefdead66c8',
    messagingSenderId: '988144449753',
    projectId: 'animation-170f1',
    databaseURL: 'https://animation-170f1-default-rtdb.firebaseio.com',
    storageBucket: 'animation-170f1.firebasestorage.app',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZjWFf4vcso4imGJbE9o7pyGK0Z_ZA5yc',
    appId: '1:988144449753:ios:904afbdc99afefdead66c8',
    messagingSenderId: '988144449753',
    projectId: 'animation-170f1',
    databaseURL: 'https://animation-170f1-default-rtdb.firebaseio.com',
    storageBucket: 'animation-170f1.firebasestorage.app',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBsEMFmu2w8PqtTTle-PHhvBkdH30Tny8',
    appId: '1:988144449753:web:1e8e1b2757a86fc0ad66c8',
    messagingSenderId: '988144449753',
    projectId: 'animation-170f1',
    authDomain: 'animation-170f1.firebaseapp.com',
    databaseURL: 'https://animation-170f1-default-rtdb.firebaseio.com',
    storageBucket: 'animation-170f1.firebasestorage.app',
    measurementId: 'G-66XWB0G7QJ',
  );
}
